language: generic

sudo: false

env:
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask install

script:
  - cask emacs -Q --batch -l ert -l alert-pstoast.el -l alert-pstoast-tests.el -f ert-run-tests-batch-and-exit
